'use client'
import { useState } from 'react'
import { useSearchParams, useRouter } from 'next/navigation'
import { api } from '@/lib/api'

export default function ReportPage() {
  const params = useSearchParams()
  const router = useRouter()
  const scenarioId = params.get('scenario_id') || ''
  const runId = params.get('run_id') || ''

  const [loading, setLoading] = useState(false)
  const [report, setReport] = useState<any>(null)
  const [error, setError] = useState<string | null>(null)

  const generate = async () => {
    setLoading(true)
    setError(null)
    try {
      const res = await api.generateReport(scenarioId, runId)
      setReport(res)
    } catch (e: any) {
      setError(e.message)
    } finally {
      setLoading(false)
    }
  }

  return (
    <div className="min-h-screen bg-gradient-maritime">
      {/* Topbar */}
      <div className="bg-bg-panel border-b border-border-dim px-6 py-3 flex items-center justify-between">
        <div className="flex items-center gap-4">
          <span className="font-display text-accent-bright">MARITIME</span>
          <span className="text-text-muted text-sm">/ Decision Report</span>
        </div>
        <div className="flex gap-3">
          <button className="btn-ghost" onClick={() => router.back()}>← Strategy</button>
          {report && (
            <a
              href={api.downloadReport(report.id)}
              download
              className="btn-primary"
            >
              ⬇️ Download Report
            </a>
          )}
        </div>
      </div>

      <div className="max-w-4xl mx-auto p-8">
        {!report && !loading && (
          <div className="card p-10 text-center">
            <div className="text-5xl mb-4">📄</div>
            <h1 className="section-title mb-3">Executive Decision Report</h1>
            <p className="text-sm text-text-secondary mb-6 max-w-md mx-auto">
              Gemini will generate a structured executive report based on the optimizer results.
              All numbers come from the deterministic optimization engine — Gemini only provides narrative.
            </p>
            <div className="flex items-center justify-center gap-2 mb-6">
              <span className="badge badge-confirmed">CONFIRMED data only</span>
              <span className="badge badge-calculated">CALCULATED results</span>
              <span className="badge badge-simulated">SIMULATED where noted</span>
            </div>
            <button className="btn-primary px-8 py-3 text-base" onClick={generate} disabled={!runId}>
              🤖 Generate Report with Gemini
            </button>
            {!runId && (
              <p className="text-xs text-reject mt-3">Run the optimizer first to generate a report.</p>
            )}
          </div>
        )}

        {loading && (
          <div className="card p-10 text-center">
            <div className="text-4xl mb-4 animate-spin-slow">⚙️</div>
            <div className="text-text-secondary">Gemini is generating your report...</div>
            <div className="text-xs text-text-muted mt-2">This may take 10–20 seconds</div>
          </div>
        )}

        {error && (
          <div className="mb-4 p-3 bg-reject/10 border border-reject/30 rounded-btn text-sm text-reject">{error}</div>
        )}

        {report && (
          <div className="space-y-4">
            <div className="flex items-center justify-between">
              <div>
                <div className="section-title">Decision Report</div>
                <div className="text-xs text-text-muted mt-1">
                  Generated by: {report.generated_by} · {report.model_used || 'template'} · {new Date(report.created_at).toLocaleString()}
                </div>
              </div>
              <a href={api.downloadReport(report.id)} download className="btn-primary">
                ⬇️ Download .md
              </a>
            </div>

            <div className="card p-8">
              <div
                className="prose prose-invert prose-sm max-w-none
                  prose-headings:font-display prose-headings:text-text-primary
                  prose-p:text-text-secondary prose-strong:text-text-primary
                  prose-table:text-sm prose-td:border-border-dim prose-th:border-border-dim
                  prose-code:text-accent-bright"
                dangerouslySetInnerHTML={{
                  __html: markdownToHtml(report.report_markdown || '')
                }}
              />
            </div>
          </div>
        )}
      </div>
    </div>
  )
}

// Minimal markdown renderer (avoids adding remark/rehype dependency)
function markdownToHtml(md: string): string {
  return md
    .replace(/^# (.+)$/gm, '<h1 class="text-2xl font-display text-text-primary mb-4 mt-0">$1</h1>')
    .replace(/^## (.+)$/gm, '<h2 class="text-lg font-display text-text-primary mb-3 mt-6 pb-1 border-b border-border-dim">$2</h2>')
    .replace(/^### (.+)$/gm, '<h3 class="text-base font-semibold text-text-primary mb-2 mt-4">$1</h3>')
    .replace(/\*\*(.+?)\*\*/g, '<strong class="text-text-primary">$1</strong>')
    .replace(/`(.+?)`/g, '<code class="text-accent-bright bg-bg-surface px-1 py-0.5 rounded text-xs">$1</code>')
    .replace(/^\| (.+) \|$/gm, (line) => {
      const cells = line.split('|').slice(1, -1).map(c => c.trim())
      const isSep = cells.every(c => /^[-:]+$/.test(c))
      if (isSep) return ''
      return `<tr class="border-b border-border-dim">${cells.map(c => `<td class="px-3 py-2 text-sm text-text-secondary">${c}</td>`).join('')}</tr>`
    })
    .replace(/(<tr.*<\/tr>)/gs, '<table class="w-full border-collapse mb-4">$1</table>')
    .replace(/^(?!<[h|t|u|o])(.+)$/gm, '<p class="text-text-secondary text-sm mb-2 leading-relaxed">$1</p>')
    .replace(/---/g, '<hr class="border-border-dim my-6" />')
    .replace(/\n\n/g, '')
}
