'use client'

import { useState, Suspense } from 'react'
import { useSearchParams, useRouter } from 'next/navigation'
import { Navbar } from '@/components/ui/Navbar'
import { GlassPanel } from '@/components/ui/GlassPanel'
import { GlassBadge } from '@/components/ui/GlassBadge'
import { api } from '@/lib/api'

function ReportContent() {
  const searchParams = useSearchParams()
  const router = useRouter()
  const scenarioId = searchParams.get('scenario_id') || ''
  const runId = searchParams.get('run_id') || ''

  const [loading, setLoading] = useState(false)
  const [report, setReport] = useState<any>(null)
  const [error, setError] = useState<string | null>(null)

  const generate = async () => {
    setLoading(true)
    setError(null)
    try {
      const res = await api.generateReport(scenarioId, runId)
      setReport(res)
    } catch (e: any) {
      setError(e.message)
    } finally {
      setLoading(false)
    }
  }

  return (
    <div className="min-h-screen flex flex-col">
      <Navbar scenarioId={scenarioId} />

      <main className="flex-1 max-w-4xl w-full mx-auto p-4 sm:p-6 lg:p-8 space-y-8 animate-fade-in">
        <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4">
          <div>
            <div className="flex items-center gap-3 mb-1">
              <span className="text-xs uppercase tracking-widest text-[#8aacca] font-semibold">
                Executive Decision Briefing
              </span>
              <GlassBadge status="CONFIRMED" label="Provenanced" />
            </div>
            <h1 className="title-ogg text-3xl sm:text-4xl text-[#fdf1e1]">
              Maritime Supply Decision Report
            </h1>
          </div>

          <div className="flex items-center gap-3">
            <button className="btn-ghost-glass" onClick={() => router.back()}>
              ← Strategy
            </button>
            {report && (
              <a
                href={api.downloadReport(report.id)}
                download
                className="btn-paper px-6 py-2.5 text-sm font-semibold inline-flex items-center gap-2"
              >
                ⬇️ Download Decision Report (.md)
              </a>
            )}
          </div>
        </div>

        {error && (
          <div className="p-4 rounded-xl bg-[#ef4444]/15 border border-[#ef4444]/40 text-sm text-[#ef4444]">
            ⚠️ {error}
          </div>
        )}

        {!report && !loading && (
          <GlassPanel className="text-center py-12 space-y-6">
            <div className="text-5xl">📄</div>
            <div className="space-y-2 max-w-md mx-auto">
              <h2 className="title-ogg text-2xl text-[#fdf1e1]">
                Generate Executive Decision Report
              </h2>
              <p className="text-sm text-[#8aacca]">
                Gemini will synthesize your scenario requirements, confirmed commercial deal terms, and OR-Tools optimization results into a structured decision document.
              </p>
            </div>

            <div className="flex items-center justify-center gap-3 flex-wrap">
              <GlassBadge status="CONFIRMED" label="Verified Deals" />
              <GlassBadge status="CALCULATED" label="Math Solved" />
              <GlassBadge status="SIMULATED" label="Market Prices" />
            </div>

            <button
              onClick={generate}
              disabled={!runId}
              className="btn-paper text-base px-8 py-3.5 font-semibold"
            >
              🤖 Generate Report with Gemini →
            </button>

            {!runId && (
              <div className="text-xs text-[#ef4444]">
                Please run the OR-Tools optimizer first to generate a report.
              </div>
            )}
          </GlassPanel>
        )}

        {loading && (
          <GlassPanel className="text-center py-16 space-y-4">
            <div className="text-4xl animate-spin">⚙️</div>
            <div className="text-[#fdf1e1] font-semibold text-lg">Synthesizing Decision Briefing...</div>
            <div className="text-xs text-[#8aacca]">Gemini is assembling Markdown report with exact provenance tags.</div>
          </GlassPanel>
        )}

        {report && (
          <GlassPanel className="p-8 sm:p-10 space-y-6">
            <div className="flex items-center justify-between border-b border-[rgba(30,90,140,0.3)] pb-4">
              <div>
                <span className="text-xs text-[#6b8499] uppercase tracking-wider block">Document ID</span>
                <span className="font-mono text-xs text-[#2a9aff]">{report.id}</span>
              </div>
              <div className="text-right">
                <span className="text-xs text-[#6b8499] uppercase tracking-wider block">Generated By</span>
                <span className="text-xs text-[#fdf1e1] font-medium">{report.generated_by} · {report.model_used || 'Template'}</span>
              </div>
            </div>

            <div
              className="prose prose-invert max-w-none space-y-4
                prose-headings:title-ogg prose-headings:text-[#fdf1e1]
                prose-h1:text-3xl prose-h2:text-xl prose-h2:border-b prose-h2:border-[rgba(30,90,140,0.3)] prose-h2:pb-2 prose-h2:mt-6
                prose-p:text-[#e2eaf4] prose-p:text-sm prose-p:leading-relaxed
                prose-strong:text-[#fdf1e1] prose-strong:font-semibold
                prose-table:w-full prose-table:text-sm prose-td:py-2.5 prose-td:px-3 prose-td:border-b prose-td:border-[rgba(30,90,140,0.2)] prose-th:py-2 prose-th:px-3 prose-th:text-xs prose-th:uppercase prose-th:text-[#8aacca]
                prose-code:text-[#2a9aff] prose-code:bg-[#0a121c] prose-code:px-1.5 prose-code:py-0.5 prose-code:rounded"
              dangerouslySetInnerHTML={{
                __html: markdownToHtml(report.report_markdown || ''),
              }}
            />

            <div className="pt-6 border-t border-[rgba(30,90,140,0.3)] flex justify-end">
              <a
                href={api.downloadReport(report.id)}
                download
                className="btn-paper text-sm px-6 py-3 font-semibold"
              >
                ⬇️ Download Official Decision Report (.md)
              </a>
            </div>
          </GlassPanel>
        )}
      </main>
    </div>
  )
}

export default function ReportPage() {
  return (
    <Suspense fallback={<div className="min-h-screen bg-[#080e14] flex items-center justify-center text-[#8aacca]">Loading Report...</div>}>
      <ReportContent />
    </Suspense>
  )
}

function markdownToHtml(md: string): string {
  return md
    .replace(/^# (.+)$/gm, '<h1 class="text-3xl font-normal text-[#fdf1e1] mb-4">$1</h1>')
    .replace(/^## (.+)$/gm, '<h2 class="text-xl font-normal text-[#fdf1e1] mt-6 mb-3 border-b border-[rgba(30,90,140,0.3)] pb-2">$2</h2>')
    .replace(/^### (.+)$/gm, '<h3 class="text-base font-semibold text-[#2a9aff] mt-4 mb-2">$1</h3>')
    .replace(/\*\*(.+?)\*\*/g, '<strong class="text-[#fdf1e1] font-semibold">$1</strong>')
    .replace(/`(.+?)`/g, '<code class="text-[#2a9aff] bg-[#0a121c] px-1.5 py-0.5 rounded text-xs">$1</code>')
    .replace(/^\| (.+) \|$/gm, (line) => {
      const cells = line.split('|').slice(1, -1).map((c) => c.trim())
      const isSep = cells.every((c) => /^[-:]+$/.test(c))
      if (isSep) return ''
      return `<tr>${cells.map((c) => `<td>${c}</td>`).join('')}</tr>`
    })
    .replace(/(<tr[\s\S]*<\/tr>)/g, '<table class="w-full my-4"><tbody>$1</tbody></table>')
    .replace(/^(?!<[h|t|u|o])(.+)$/gm, '<p class="text-sm text-[#e2eaf4] leading-relaxed mb-3">$1</p>')
    .replace(/---/g, '<hr class="border-[rgba(30,90,140,0.3)] my-6" />')
}
